version: '3.7'
services:

  openvpn:
    image: kylemanna/openvpn:2.4
    container_name: openvpn
    volumes:
      - ~/.data/openvpn/data:/etc/openvpn
    ports:
      - 1194:1194/udp
    cap_add:
      - NET_ADMIN
    network_mode: "host"