version: '3.7'
services:

  openvpn-client:
    image: monve/openvpnclient:latest
    container_name: openvpn-client
    privileged: true
    volumes:
      - ~/.data/openvpn-client/vpn:/root/vpn
    network_mode: "host"