version: '3'

# docker network create nginx_bridge
networks:
  nginx_bridge:
    driver: bridge

services:
  nginx:
    image: monve/nginx:latest
    container_name: nginx
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai 
    ports:
      - 8080:80
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/.data/nginx/conf.d:/etc/nginx/conf.d
      - ~/.data/nginx/html/:/usr/share/nginx/html/
      - ~/.data/nginx/log:/var/log/nginx
      - ~/.data/nginx/config:/root/config
      - ~/.data/nginx/letsencrypt:/etc/letsencrypt
    networks:
      - nginx_bridge