version: '3.7'
services:
  openldap:
    image: osixia/openldap:stable
    container_name: openldap
    hostname: openldap
    volumes:
      - ~/.data/openldap/certificates:/container/service/slapd/assets/certs
      - ~/.data/openldap/database:/var/lib/ldap
      - ~/.data/openldap/config:/etc/ldap/slapd.d
    environment: 
      - LDAP_ORGANISATION=dibiaozuitu
      - LDAP_DOMAIN=dibiaozuitu.com
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin_pass
      - LDAP_CONFIG_PASSWORD=config_pass
      - "LDAP_BASE_DN=dc=dibiaozuitu,dc=com"
      - LDAP_TLS_CRT_FILENAME=server.crt
      - LDAP_TLS_KEY_FILENAME=server.key
      - LDAP_TLS_CA_CRT_FILENAME=dibiaozuitu.com.ca.crt
  
  phpldapadmin:
    image: osixia/phpldapadmin:stable
    container_name: phpldapadmin
    hostname: phpldapadmin
    ports: 
      - "10001:80"
    environment: 
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    depends_on:
      - openldap