version: '3.7'

networks:
  nginx_net_bridge:
    external: true
  net_bridge:
    driver: bridge

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_AUTHPROVIDER.1: org.apache.zookeeper.server.auth.SASLAuthenticationProvider
      SERVER_JVMFLAGS: -Djava.security.auth.login.config=/etc/kafka/secrets/zk_server_jaas.conf
    volumes:
      - ~/.data/kafka/secrets:/etc/kafka/secrets
    networks:
      - net_bridge

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    networks:
      - net_bridge
      - nginx_net_bridge
    env_file:
      - ~/.data/kafka/.env
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: SASL_PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://${OUTSIDE_HOSTNAME}:9092
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms16M"
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.auth.SimpleAclAuthorizer
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/kafka_server_jaas.conf
      KAFKA_SUPER_USERS: User:admin
      KAFKA_LOG_DIRS: /data/kafka-data
    volumes:
      - ~/.data/kafka/secrets:/etc/kafka/secrets
      - ~/.data/kafka/data:/data/kafka-data

  kafka_manager:
    image: hlebalbau/kafka-manager:stable
    container_name: kafka_manager
    ports:
      - 9000:9000
    environment:
      ZK_HOSTS: "zookeeper:2181"
    env_file:
      - ~/.data/kafka/.env
    networks:
      - net_bridge
    depends_on:
      - zookeeper
      - kafka
