version: '3.7'

networks:
  net_bridge:
    driver: bridge

services:
  mongo:
    image: mongo:5.0.2
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes: 
      - ~/.data/mongo/data/db:/data/db
      - ~/.data/mongo/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    command: mongod
    networks:
      - net_bridge